import type { CaseRecord } from "./contracts";
import { blockedDecision } from "./fixtures";

/**
 * DEMO DATA — deterministic case queue shaped like the case API. The first
 * record is the case opened by the blocked wire in the decision fixture.
 */
export const caseFixtures: CaseRecord[] = [
  {
    caseId: "CASE-88419",
    decisionId: blockedDecision.decisionId,
    transactionId: blockedDecision.transactionId,
    customerId: blockedDecision.customerId,
    amount: blockedDecision.amount,
    currency: blockedDecision.currency,
    verdict: "BLOCK",
    riskScore: blockedDecision.riskScore,
    priority: "P1",
    status: "IN_REVIEW",
    outcome: null,
    assignee: "a.sharma",
    openedBy: blockedDecision.policy,
    openedAt: "2026-08-22T17:41:09.284Z",
    updatedAt: "2026-08-22T17:58:02.110Z",
    slaMinutesRemaining: 221,
    summary:
      "Outbound IMPS payout of ₹14,50,000 INR blocked after six independent risk signals exceeded the policy threshold.",
    timeline: [
      {
        id: "ev_1",
        at: "2026-08-22T17:41:09.284Z",
        actor: blockedDecision.policy,
        actorKind: "SYSTEM",
        text: "Case opened at P1 — decision dec_01HZK4JR7T2QW8 returned BLOCK at score 0.96.",
      },
      {
        id: "ev_2",
        at: "2026-08-22T17:41:09.402Z",
        actor: "graph-service",
        actorKind: "SYSTEM",
        text: "Entity resolution linked payee PA-77120 to 14 synthetic accounts in active mule ring.",
      },
      {
        id: "ev_3",
        at: "2026-08-22T17:43:18.000Z",
        actor: "ropus-agent",
        actorKind: "AI",
        text: "Inferred account-takeover pattern: headless Linux emulator, datacenter proxy ASN, and beneficiary added 9 minutes before payout.",
      },
      {
        id: "ev_4",
        at: "2026-08-22T17:49:31.000Z",
        actor: "a.sharma",
        actorKind: "ANALYST",
        text: "Assigned to self and opened the fraud graph for payee neighbourhood.",
      },
      {
        id: "ev_5",
        at: "2026-08-22T17:58:02.110Z",
        actor: "a.sharma",
        actorKind: "ANALYST",
        text: "Requested outbound corporate callback verification before confirming permanent block.",
      },
    ],
  },
  {
    caseId: "CASE-88407",
    decisionId: "dec_01HZK2P4M9F3AC",
    transactionId: "txn_5b81de20c4",
    customerId: "cus_2210873",
    amount: 24800,
    currency: "INR",
    verdict: "REVIEW",
    riskScore: 0.62,
    priority: "P2",
    status: "OPEN",
    outcome: null,
    assignee: null,
    openedBy: "pol_upi_collect_v3",
    openedAt: "2026-08-22T15:22:04.000Z",
    updatedAt: "2026-08-22T15:22:04.000Z",
    slaMinutesRemaining: 46,
    summary:
      "UPI collect request flagged for velocity across three digital banking apps within nine minutes.",
    timeline: [
      {
        id: "ev_1",
        at: "2026-08-22T15:22:04.000Z",
        actor: "pol_upi_collect_v3",
        actorKind: "SYSTEM",
        text: "Case opened at P2 — decision returned REVIEW at score 0.62.",
      },
    ],
  },
  {
    caseId: "CASE-88392",
    decisionId: "dec_01HZJX9K1B7RT0",
    transactionId: "txn_1c04ff9a63",
    customerId: "cus_9930145",
    amount: 7800,
    currency: "INR",
    verdict: "CHALLENGE",
    riskScore: 0.48,
    priority: "P3",
    status: "CLOSED",
    outcome: "BENIGN_CONFIRMED",
    assignee: "r.verma",
    openedBy: "pol_imps_payout_v7",
    openedAt: "2026-08-22T11:04:52.000Z",
    updatedAt: "2026-08-22T11:22:18.000Z",
    slaMinutesRemaining: 0,
    summary: "IMPS payout to a new VPA challenged with SMS OTP and verified by user.",
    timeline: [
      {
        id: "ev_1",
        at: "2026-08-22T11:04:52.000Z",
        actor: "pol_imps_payout_v7",
        actorKind: "SYSTEM",
        text: "Step-up OTP challenge issued to customer device.",
      },
      {
        id: "ev_2",
        at: "2026-08-22T11:22:18.000Z",
        actor: "r.verma",
        actorKind: "ANALYST",
        text: "OTP verified successfully. Marked as benign.",
      },
    ],
  },
  {
    caseId: "CASE-88361",
    decisionId: "dec_01HZJQ3D8V5NM6",
    transactionId: "txn_7ae2b1d905",
    customerId: "cus_5518722",
    amount: 53200,
    currency: "INR",
    verdict: "BLOCK",
    riskScore: 0.81,
    priority: "P2",
    status: "CLOSED",
    outcome: "RELEASED",
    assignee: "r.verma",
    openedBy: "pol_imps_payout_v7",
    openedAt: "2026-08-21T19:33:10.000Z",
    updatedAt: "2026-08-21T20:07:44.000Z",
    slaMinutesRemaining: 0,
    summary: "Block reversed after the customer verified the payee over an authenticated callback.",
    timeline: [
      {
        id: "ev_1",
        at: "2026-08-21T19:33:10.000Z",
        actor: "pol_wire_outbound_v7",
        actorKind: "SYSTEM",
        text: "Case opened at P2 — decision returned BLOCK at score 0.81.",
      },
      {
        id: "ev_2",
        at: "2026-08-21T20:07:44.000Z",
        actor: "j.lindqvist",
        actorKind: "ANALYST",
        text: "Payee verified over authenticated callback. Transaction released to settlement; case closed.",
      },
    ],
  },
];

export const caseById = (id: string) => caseFixtures.find((c) => c.caseId === id);
