import type { FraudGraph } from "./contracts";

/**
 * DEMO DATA — deterministic neighbourhood for decision dec_01HZK4JR7T2QW8.
 * Shapes match the backend graph endpoint; nothing here is generated at runtime.
 */
export const fraudGraph: FraudGraph = {
  rootId: "cus_4471029",
  decisionId: "dec_01HZK4JR7T2QW8",
  entities: [
    {
      id: "cus_4471029",
      type: "CUSTOMER",
      label: "Customer under review",
      risk: "SUSPECT",
      x: 22,
      y: 50,
      hop: 0,
      firstSeen: "2025-06-04",
      lastSeen: "2026-08-22 17:41 UTC",
      attributes: [
        ["Account age", "445 days"],
        ["Home region", "Bengaluru, KA"],
        ["Open cases", "1"],
      ],
      signals: [
        "Session originated on an unrecognised emulator device 6 minutes before payout.",
        "Beneficiary payout account added 9 minutes before transfer.",
      ],
    },
    {
      id: "txn_9f3c21ab7d",
      type: "TRANSACTION",
      label: "IMPS Payout · ₹14,50,000 INR",
      risk: "SUSPECT",
      x: 50,
      y: 50,
      hop: 1,
      firstSeen: "2026-08-22 17:41 UTC",
      lastSeen: "2026-08-22 17:41 UTC",
      attributes: [
        ["Amount", "₹14,50,000.00 INR"],
        ["Channel", "imps_payout"],
        ["Verdict", "BLOCK"],
      ],
      signals: ["Blocked at 17:41:09 UTC by policy pol_imps_payout_v7."],
    },
    {
      id: "dvc_5b91e0",
      type: "DEVICE",
      label: "Headless Linux emulator",
      risk: "WATCH",
      x: 34,
      y: 20,
      hop: 1,
      firstSeen: "2026-08-22 17:35 UTC",
      lastSeen: "2026-08-22 17:41 UTC",
      attributes: [
        ["Fingerprint age", "6 minutes"],
        ["Platform", "Linux x86_64 / Headless Chrome"],
        ["Linked customers", "14"],
      ],
      signals: ["Device canvas hash 9f8a84b12c observed across 14 synthetic mule accounts."],
    },
    {
      id: "198.51.100.44",
      type: "IP",
      label: "Datacenter proxy origin",
      risk: "SUSPECT",
      x: 34,
      y: 80,
      hop: 1,
      firstSeen: "2026-04-11",
      lastSeen: "2026-08-22 17:41 UTC",
      attributes: [
        ["ASN", "ASN 13335"],
        ["Reputation", "malicious hosting"],
        ["Proxy / VPN / Tor", "yes · yes · no"],
      ],
      signals: ["Geolocated to Limassol proxy while active baseline resolves to Bengaluru, KA."],
    },
    {
      id: "PA-77120",
      type: "ACCOUNT",
      label: "Beneficiary payout mule account",
      risk: "CONFIRMED_FRAUD",
      x: 74,
      y: 50,
      hop: 2,
      firstSeen: "2026-02-18",
      lastSeen: "2026-08-22 17:41 UTC",
      attributes: [
        ["Linked customers", "14"],
        ["Confirmed fraud links", "3"],
        ["Institution", "ICICI / HDFC Mule Payout Node"],
      ],
      signals: [
        "Shared with 13 other synthetic customer accounts across this tenant.",
        "Three linked accounts have confirmed fraud outcomes.",
      ],
    },
    {
      id: "cus_8830114",
      type: "CUSTOMER",
      label: "Linked account · confirmed fraud",
      risk: "CONFIRMED_FRAUD",
      x: 90,
      y: 26,
      hop: 3,
      firstSeen: "2026-03-02",
      lastSeen: "2026-07-19",
      attributes: [
        ["Outcome", "confirmed fraud"],
        ["Closed case", "CASE-81204"],
      ],
      signals: ["Fraud chargeback confirmed on 2026-07-19 against the same payout account."],
    },
    {
      id: "cus_2201477",
      type: "CUSTOMER",
      label: "Linked account · under review",
      risk: "WATCH",
      x: 90,
      y: 74,
      hop: 3,
      firstSeen: "2026-05-27",
      lastSeen: "2026-08-20",
      attributes: [
        ["Outcome", "under review"],
        ["Open case", "CASE-88402"],
      ],
      signals: ["Two payouts to PA-77120 in the last 30 days."],
    },
  ],
  relationships: [
    { source: "cus_4471029", target: "txn_9f3c21ab7d", label: "initiated", onDecisionPath: true },
    {
      source: "cus_4471029",
      target: "dvc_5b91e0",
      label: "authenticated on",
      onDecisionPath: true,
    },
    {
      source: "cus_4471029",
      target: "198.51.100.44",
      label: "session origin",
      onDecisionPath: true,
    },
    { source: "dvc_5b91e0", target: "198.51.100.44", label: "observed together" },
    { source: "txn_9f3c21ab7d", target: "PA-77120", label: "pays out to", onDecisionPath: true },
    { source: "PA-77120", target: "cus_8830114", label: "shared with" },
    { source: "PA-77120", target: "cus_2201477", label: "shared with" },
  ],
};
