import type { DecisionListItem, OverviewMetrics } from "./contracts";
import { approvedDecision, blockedDecision } from "./fixtures";

/** DEMO DATA — deterministic decision feed shaped like GET /v1/risk/decisions. */
export const decisionList: DecisionListItem[] = [
  {
    decisionId: blockedDecision.decisionId,
    transactionId: blockedDecision.transactionId,
    customerId: blockedDecision.customerId,
    amount: blockedDecision.amount,
    currency: blockedDecision.currency,
    verdict: "BLOCK",
    riskScore: blockedDecision.riskScore,
    primarySignal: "Beneficiary payout node shared with 14-mule syndicate",
    latencyMs: blockedDecision.latencyMs,
    caseId: blockedDecision.caseId,
    evaluatedAt: blockedDecision.evaluatedAt,
  },
  {
    decisionId: "dec_01HZK2P4M9F3AC",
    transactionId: "txn_5b81de20c4",
    customerId: "cus_2210873",
    amount: 24800,
    currency: "INR",
    verdict: "REVIEW",
    riskScore: 0.62,
    primarySignal: "UPI collect request velocity across three apps in 9m",
    latencyMs: 31.7,
    caseId: "CASE-88407",
    evaluatedAt: "2026-08-22T15:22:03.880Z",
  },
  {
    decisionId: "dec_01HZJX9K1B7RT0",
    transactionId: "txn_1c04ff9a63",
    customerId: "cus_9930145",
    amount: 7800,
    currency: "INR",
    verdict: "CHALLENGE",
    riskScore: 0.48,
    primarySignal: "New VPA beneficiary on high-velocity IMPS rail",
    latencyMs: 27.2,
    caseId: "CASE-88392",
    evaluatedAt: "2026-08-22T11:04:51.640Z",
  },
  {
    decisionId: "dec_01HZJQ3D8V5NM6",
    transactionId: "txn_7ae2b1d905",
    customerId: "cus_5518722",
    amount: 53200,
    currency: "INR",
    verdict: "BLOCK",
    riskScore: 0.81,
    primarySignal: "Card-not-present amount surge deviates +412% from profile",
    latencyMs: 35.9,
    caseId: "CASE-88361",
    evaluatedAt: "2026-08-21T19:33:09.510Z",
  },
  {
    decisionId: approvedDecision.decisionId,
    transactionId: approvedDecision.transactionId,
    customerId: approvedDecision.customerId,
    amount: approvedDecision.amount,
    currency: approvedDecision.currency,
    verdict: "APPROVE",
    riskScore: approvedDecision.riskScore,
    primarySignal: "Trusted Jio Fiber IP, established UPI payee",
    latencyMs: approvedDecision.latencyMs,
    caseId: approvedDecision.caseId,
    evaluatedAt: approvedDecision.evaluatedAt,
  },
  {
    decisionId: "dec_01HZJH7C2X4KP1",
    transactionId: "txn_44b9ce1207",
    customerId: "cus_1180644",
    amount: 385.0,
    currency: "INR",
    verdict: "APPROVE",
    riskScore: 0.07,
    primarySignal: "Blinkit Quick Commerce, matched mobile device",
    latencyMs: 22.8,
    caseId: null,
    evaluatedAt: "2026-08-21T14:02:40.120Z",
  },
];

/** DEMO DATA — aggregate counters shaped like GET /v1/metrics/overview. */
export const overviewMetrics: OverviewMetrics = {
  windowLabel: "Last 24 hours",
  evaluations: 1284392,
  blockRate: 0.0091,
  reviewRate: 0.0234,
  p99LatencyMs: 62.4,
  openCases: 24,
  distribution: [
    { verdict: "APPROVE", count: 1240118 },
    { verdict: "REVIEW", count: 30055 },
    { verdict: "CHALLENGE", count: 2531 },
    { verdict: "BLOCK", count: 11688 },
  ],
  services: [
    { name: "Decision API", state: "HEALTHY", p99Ms: 62.4, detail: "Synchronous evaluation path" },
    { name: "Rules engine", state: "HEALTHY", p99Ms: 8.1, detail: "pol_wire_outbound_v7 active" },
    { name: "Model serving", state: "HEALTHY", p99Ms: 19.6, detail: "ropus-risk-xgb v4.2.1" },
    { name: "Graph service", state: "DEGRADED", p99Ms: 411.0, detail: "3-hop traversals queued" },
    { name: "Decision stream", state: "DEGRADED", p99Ms: 0, detail: "Consumer lag on partition 6" },
    { name: "Webhook delivery", state: "HEALTHY", p99Ms: 148.2, detail: "No endpoints in backoff" },
  ],
};
