/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as DecisionsIndexRouteImport } from './routes/decisions.index'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions.$decisionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/demo': typeof DemoRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/models': typeof ModelsRoute
  '/operations': typeof OperationsRoute
  '/rules': typeof RulesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/webhooks': typeof WebhooksRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/cases/': typeof CasesIndexRoute
  '/decisions/': typeof DecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/demo': typeof DemoRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/models': typeof ModelsRoute
  '/operations': typeof OperationsRoute
  '/rules': typeof RulesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/webhooks': typeof WebhooksRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/cases': typeof CasesIndexRoute
  '/decisions': typeof DecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/demo': typeof DemoRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/models': typeof ModelsRoute
  '/operations': typeof OperationsRoute
  '/rules': typeof RulesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/webhooks': typeof WebhooksRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/cases/': typeof CasesIndexRoute
  '/decisions/': typeof DecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/api-keys'
    | '/demo'
    | '/graph'
    | '/investigations'
    | '/models'
    | '/operations'
    | '/rules'
    | '/security'
    | '/settings'
    | '/threat-intelligence'
    | '/webhooks'
    | '/cases/$caseId'
    | '/decisions/$decisionId'
    | '/cases/'
    | '/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/api-keys'
    | '/demo'
    | '/graph'
    | '/investigations'
    | '/models'
    | '/operations'
    | '/rules'
    | '/security'
    | '/settings'
    | '/threat-intelligence'
    | '/webhooks'
    | '/cases/$caseId'
    | '/decisions/$decisionId'
    | '/cases'
    | '/decisions'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/api-keys'
    | '/demo'
    | '/graph'
    | '/investigations'
    | '/models'
    | '/operations'
    | '/rules'
    | '/security'
    | '/settings'
    | '/threat-intelligence'
    | '/webhooks'
    | '/cases/$caseId'
    | '/decisions/$decisionId'
    | '/cases/'
    | '/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DemoRoute: typeof DemoRoute
  GraphRoute: typeof GraphRoute
  InvestigationsRoute: typeof InvestigationsRoute
  ModelsRoute: typeof ModelsRoute
  OperationsRoute: typeof OperationsRoute
  RulesRoute: typeof RulesRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
  WebhooksRoute: typeof WebhooksRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/': {
      id: '/decisions/'
      path: '/decisions'
      fullPath: '/decisions/'
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ApiKeysRoute: ApiKeysRoute,
  DemoRoute: DemoRoute,
  GraphRoute: GraphRoute,
  InvestigationsRoute: InvestigationsRoute,
  ModelsRoute: ModelsRoute,
  OperationsRoute: OperationsRoute,
  RulesRoute: RulesRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
  WebhooksRoute: WebhooksRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
