apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risk-manager.fullname" . }}-secrets
  labels:
    {{- include "risk-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
